### ISSUE TITLE
Design the public API for the topic-based messaging

### ISSUE THREAD

**Issue by raksanyi** [Isabelle2048/CorEstafette#5]
For step one, we need to have these 3 methods:

- Subscribe: For the clients to be able to subscribe to a topic with a callback
- Unsubscribe: For the clients to be able to unsubscribe from a topic
- Publish: For clients to be able to publish a message to a topic

Topic are strings, messages need to be serialized to JSON-s before interacting with the service.

**Comment by Isabelle2048** [comment]
Created message in js.

**Comment by Isabelle2048** [comment]
The APIs for communicators on the WebClient side to achieve these tasks: 

publish: (topic: string, message: string) => void;
subscribeAsync: (topic: string, topicCallback: (message: IMessage) => any) => Promise\<IResponse\>;
unsubscribeAsync: (topic: string) => Promise\<IResponse\>;

For subscribeAsync and unsubscribeAsync, communicator wait for a response from the service and send it back to the client. Publish is fired & forgot. Upon subscription, a callback passed by the client is cached in the communicator, which will be triggered when receiving a message under that topic.
